/*
 * Script Name: 02-main-core.tf
 * Project Name: Primus
 * Description: Provisions core shared infrastructure services required by the EKS cluster.
 * This includes the KMS Customer Managed Key (CMK) for encryption and
 * the CloudWatch Log Group for control plane logging, optional SSH keys, and secure storage.
 *
 * ------------------------
 * Architectural Decisions:
 * ------------------------
 * - Encryption at Rest: Uses a dedicated KMS CMK to encrypt Kubernetes secrets (envelope encryption)
 * and CloudWatch logs, ensuring data security and compliance.
 * - Centralized Logging: Provisions a specific CloudWatch Log Group to capture EKS control plane
 * logs (API, Audit, Authenticator, etc.) for observability.
 * - Node Access: Optionally provisions an SSH Key Pair for emergency worker node access
 * (break-glass scenario).
 * - Secure Storage: Provisions a private, encrypted S3 bucket to store sensitive administrative
 * assets (like kubeconfig) securely.
 */

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

/*
 * ------------------------
 * KMS CUSTOMER MANAGED KEY
 * ------------------------
 * Purpose:
 *   Provides the root of trust for encrypting sensitive data within the EKS environment.
 *
 * Usage:
 *   - Kubernetes Secrets: Used by the EKS Control Plane for envelope encryption of etcd secrets.
 *   - CloudWatch Logs: Encrypts the control plane logs stored in CloudWatch.
 */

module "eks_cluster_kms" {
  source = "../modules/security-kms"

  kms_description             = local.EKS_CLUSTER_KMS_DESC
  kms_deletion_window_in_days = 7
  kms_enable_key_rotation     = true
  kms_key_alias               = local.EKS_CLUSTER_KMS_ALIAS
  kms_admin_account_id        = data.aws_caller_identity.current.account_id
  kms_account_region          = data.aws_region.current.id
  kms_policy = templatefile("./templates/kms-key-policy.json", {
    ACCOUNT_ID = data.aws_caller_identity.current.account_id
    REGION     = data.aws_region.current.id
  })
}

/*
 * --------------------
 * CLOUDWATCH LOG GROUP
 * --------------------
 * Purpose:
 *   Stores the control plane logs generated by the EKS cluster.
 *
 * Configuration:
 *   - Naming Convention: Follows AWS standard `/aws/eks/<cluster-name>/cluster`.
 *   - Encryption: Encrypted using the provisioned KMS key.
 *   - Retention: Retains logs for 7 days to manage storage costs.
 */

resource "aws_cloudwatch_log_group" "eks_cluster" {
  name              = local.EKS_CLUSTER_LOG_GROUP
  retention_in_days = 7
  kms_key_id        = module.eks_cluster_kms.kms_key_arn
}

/*
 * ------------
 * SSH KEY PAIR
 * ------------
 * Purpose:
 *   Provides SSH access credentials for EKS worker nodes.
 *   Useful for debugging or emergency access if SSM is unavailable.
 */

resource "aws_key_pair" "eks_nodes" {
  count      = var.main_ssh_public_key != null ? 1 : 0
  key_name   = local.EKS_NODE_KEY_NAME
  public_key = var.main_ssh_public_key
}

/*
 * -------------------
 * ADMIN ASSETS BUCKET
 * -------------------
 * Purpose:
 *   Securely stores administrative assets like the generated kubeconfig file.
 *
 * Security Controls:
 *   - Encryption: Server-side encryption using the EKS Cluster KMS Key.
 *   - Access: Strictly private; blocked public access.
 */

resource "aws_s3_bucket" "eks_admin_assets" {
  bucket = local.EKS_ADMIN_BUCKET_NAME
}

resource "aws_s3_bucket_server_side_encryption_configuration" "eks_admin_assets" {
  bucket = aws_s3_bucket.eks_admin_assets.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = module.eks_cluster_kms.kms_key_arn
      sse_algorithm     = "aws:kms"
    }
  }
}

resource "aws_s3_bucket_versioning" "eks_admin_assets" {
  bucket = aws_s3_bucket.eks_admin_assets.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "eks_admin_assets" {
  bucket = aws_s3_bucket.eks_admin_assets.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
